/* ══════════════════════════════════════════════════
   CLAUDE CODE — UNIT TEST GENERATOR DEMO
   Click card Claude Code → mở modal test generator
══════════════════════════════════════════════════ */

(function () {
  'use strict';

  // ── Preset code snippets ───────────────────────
  const PRESETS = {
    calc: `function calculateDiscount(price, coupon) {\n  if (typeof price !== 'number' || price < 0) {\n    throw new Error('Invalid price');\n  }\n  const coupons = { SAVE10: 0.10, SAVE20: 0.20, VIP50: 0.50 };\n  const rate = coupons[coupon] || 0;\n  return Math.round(price * (1 - rate) * 100) / 100;\n}`,
    auth:  `async function validateUser(email, password) {\n  if (!email || !email.includes('@')) {\n    return { ok: false, error: 'Invalid email' };\n  }\n  if (!password || password.length < 8) {\n    return { ok: false, error: 'Password too short' };\n  }\n  const user = await db.findByEmail(email);\n  if (!user) return { ok: false, error: 'User not found' };\n  const match = await bcrypt.compare(password, user.hash);\n  return match ? { ok: true, user } : { ok: false, error: 'Wrong password' };\n}`,
    api:   `async function fetchProducts(categoryId, options = {}) {\n  const { limit = 20, page = 1, sortBy = 'name' } = options;\n  if (!categoryId) throw new Error('categoryId is required');\n  const url = \`/api/products?category=\${categoryId}&limit=\${limit}&page=\${page}&sort=\${sortBy}\`;\n  const res = await fetch(url);\n  if (!res.ok) throw new Error(\`HTTP \${res.status}\`);\n  return res.json();\n}`,
    cart:  `function addToCart(cart, item) {\n  if (!item?.id || !item?.price || item.price <= 0) {\n    throw new Error('Invalid item');\n  }\n  const existing = cart.find(i => i.id === item.id);\n  if (existing) {\n    return cart.map(i => i.id === item.id\n      ? { ...i, qty: i.qty + (item.qty || 1) }\n      : i);\n  }\n  return [...cart, { ...item, qty: item.qty || 1 }];\n}`,
  };

  // ── Generated test outputs ─────────────────────
  const OUTPUTS = {
    calc: {
      tests: 3, cases: 8, cov: 96,
      jest: `<span class="cc-cm">// Generated by Claude Code — calculateDiscount.test.js</span>
<span class="cc-kw">import</span> { <span class="cc-var">calculateDiscount</span> } <span class="cc-kw">from</span> <span class="cc-str">'./discount'</span>;

<span class="cc-fn">describe</span>(<span class="cc-str">'calculateDiscount'</span>, () => {

  <span class="cc-cm">// ── Happy paths ────────────────────────────</span>
  <span class="cc-fn">it</span>(<span class="cc-str">'applies 10% discount for SAVE10'</span>, () => {
    <span class="cc-fn">expect</span>(<span class="cc-fn">calculateDiscount</span>(<span class="cc-num">100</span>, <span class="cc-str">'SAVE10'</span>)).<span class="cc-fn">toBe</span>(<span class="cc-num">90</span>);
  });

  <span class="cc-fn">it</span>(<span class="cc-str">'applies 50% discount for VIP50'</span>, () => {
    <span class="cc-fn">expect</span>(<span class="cc-fn">calculateDiscount</span>(<span class="cc-num">200</span>, <span class="cc-str">'VIP50'</span>)).<span class="cc-fn">toBe</span>(<span class="cc-num">100</span>);
  });

  <span class="cc-fn">it</span>(<span class="cc-str">'returns full price for unknown coupon'</span>, () => {
    <span class="cc-fn">expect</span>(<span class="cc-fn">calculateDiscount</span>(<span class="cc-num">50</span>, <span class="cc-str">'INVALID'</span>)).<span class="cc-fn">toBe</span>(<span class="cc-num">50</span>);
  });

  <span class="cc-fn">it</span>(<span class="cc-str">'rounds result to 2 decimal places'</span>, () => {
    <span class="cc-fn">expect</span>(<span class="cc-fn">calculateDiscount</span>(<span class="cc-num">33.33</span>, <span class="cc-str">'SAVE10'</span>)).<span class="cc-fn">toBe</span>(<span class="cc-num">30</span>);
  });

  <span class="cc-cm">// ── Edge cases ─────────────────────────────</span>
  <span class="cc-fn">it</span>(<span class="cc-str">'throws on negative price'</span>, () => {
    <span class="cc-fn">expect</span>(() => <span class="cc-fn">calculateDiscount</span>(<span class="cc-num">-10</span>, <span class="cc-str">'SAVE10'</span>))
      .<span class="cc-fn">toThrow</span>(<span class="cc-str">'Invalid price'</span>);
  });

  <span class="cc-fn">it</span>(<span class="cc-str">'throws on non-numeric price'</span>, () => {
    <span class="cc-fn">expect</span>(() => <span class="cc-fn">calculateDiscount</span>(<span class="cc-str">'abc'</span>, <span class="cc-str">'SAVE10'</span>))
      .<span class="cc-fn">toThrow</span>(<span class="cc-str">'Invalid price'</span>);
  });

  <span class="cc-fn">it</span>(<span class="cc-str">'handles zero price'</span>, () => {
    <span class="cc-fn">expect</span>(<span class="cc-fn">calculateDiscount</span>(<span class="cc-num">0</span>, <span class="cc-str">'VIP50'</span>)).<span class="cc-fn">toBe</span>(<span class="cc-num">0</span>);
  });

  <span class="cc-fn">it</span>(<span class="cc-str">'handles undefined coupon'</span>, () => {
    <span class="cc-fn">expect</span>(<span class="cc-fn">calculateDiscount</span>(<span class="cc-num">100</span>, <span class="cc-kw">undefined</span>)).<span class="cc-fn">toBe</span>(<span class="cc-num">100</span>);
  });

});`,
      vitest: `<span class="cc-cm">// Generated by Claude Code — calculateDiscount.test.ts</span>
<span class="cc-kw">import</span> { <span class="cc-var">describe</span>, <span class="cc-var">it</span>, <span class="cc-var">expect</span> } <span class="cc-kw">from</span> <span class="cc-str">'vitest'</span>;
<span class="cc-kw">import</span> { <span class="cc-var">calculateDiscount</span> } <span class="cc-kw">from</span> <span class="cc-str">'./discount'</span>;

<span class="cc-fn">describe</span>(<span class="cc-str">'calculateDiscount'</span>, () => {
  <span class="cc-fn">it</span>(<span class="cc-str">'applies 10% for SAVE10'</span>, () =>
    <span class="cc-fn">expect</span>(<span class="cc-fn">calculateDiscount</span>(<span class="cc-num">100</span>, <span class="cc-str">'SAVE10'</span>)).<span class="cc-fn">toBe</span>(<span class="cc-num">90</span>));

  <span class="cc-fn">it</span>(<span class="cc-str">'throws on negative price'</span>, () =>
    <span class="cc-fn">expect</span>(() => <span class="cc-fn">calculateDiscount</span>(<span class="cc-num">-10</span>, <span class="cc-str">'SAVE10'</span>))
      .<span class="cc-fn">toThrowError</span>(<span class="cc-str">'Invalid price'</span>));

  <span class="cc-fn">it.each</span>([
    [<span class="cc-num">0</span>, <span class="cc-str">'VIP50'</span>, <span class="cc-num">0</span>],
    [<span class="cc-num">33.33</span>, <span class="cc-str">'SAVE10'</span>, <span class="cc-num">30</span>],
    [<span class="cc-num">100</span>, <span class="cc-kw">undefined</span>, <span class="cc-num">100</span>],
  ])(<span class="cc-str">'calculateDiscount(%s, %s) → %s'</span>, (price, coupon, expected) =>
    <span class="cc-fn">expect</span>(<span class="cc-fn">calculateDiscount</span>(price, coupon)).<span class="cc-fn">toBe</span>(expected));
});`,
      mocha: `<span class="cc-cm">// Generated by Claude Code — calculateDiscount.spec.js</span>
<span class="cc-kw">const</span> { <span class="cc-var">expect</span> } = <span class="cc-fn">require</span>(<span class="cc-str">'chai'</span>);
<span class="cc-kw">const</span> { <span class="cc-var">calculateDiscount</span> } = <span class="cc-fn">require</span>(<span class="cc-str">'./discount'</span>);

<span class="cc-fn">describe</span>(<span class="cc-str">'calculateDiscount'</span>, () => {
  <span class="cc-fn">it</span>(<span class="cc-str">'applies 10% for SAVE10'</span>, () =>
    <span class="cc-fn">expect</span>(<span class="cc-fn">calculateDiscount</span>(<span class="cc-num">100</span>, <span class="cc-str">'SAVE10'</span>)).<span class="cc-var">to</span>.<span class="cc-fn">equal</span>(<span class="cc-num">90</span>));

  <span class="cc-fn">it</span>(<span class="cc-str">'throws on invalid price'</span>, () =>
    <span class="cc-fn">expect</span>(() => <span class="cc-fn">calculateDiscount</span>(<span class="cc-num">-5</span>, <span class="cc-str">'SAVE10'</span>))
      .<span class="cc-var">to</span>.<span class="cc-fn">throw</span>(<span class="cc-str">'Invalid price'</span>));

  <span class="cc-fn">it</span>(<span class="cc-str">'handles unknown coupon'</span>, () =>
    <span class="cc-fn">expect</span>(<span class="cc-fn">calculateDiscount</span>(<span class="cc-num">50</span>, <span class="cc-str">'NOPE'</span>)).<span class="cc-var">to</span>.<span class="cc-fn">equal</span>(<span class="cc-num">50</span>));
});`,
    },
    auth: {
      tests: 2, cases: 7, cov: 94,
      jest: `<span class="cc-cm">// Generated by Claude Code — validateUser.test.js</span>
<span class="cc-kw">import</span> { <span class="cc-var">validateUser</span> } <span class="cc-kw">from</span> <span class="cc-str">'./auth'</span>;
<span class="cc-kw">import</span> { <span class="cc-var">db</span> } <span class="cc-kw">from</span> <span class="cc-str">'./db'</span>;
<span class="cc-kw">import</span> <span class="cc-var">bcrypt</span> <span class="cc-kw">from</span> <span class="cc-str">'bcrypt'</span>;

<span class="cc-fn">jest</span>.<span class="cc-fn">mock</span>(<span class="cc-str">'./db'</span>);
<span class="cc-fn">jest</span>.<span class="cc-fn">mock</span>(<span class="cc-str">'bcrypt'</span>);

<span class="cc-fn">describe</span>(<span class="cc-str">'validateUser'</span>, () => {

  <span class="cc-fn">beforeEach</span>(() => <span class="cc-fn">jest</span>.<span class="cc-fn">clearAllMocks</span>());

  <span class="cc-fn">it</span>(<span class="cc-str">'rejects invalid email'</span>, <span class="cc-kw">async</span> () => {
    <span class="cc-kw">const</span> <span class="cc-var">res</span> = <span class="cc-kw">await</span> <span class="cc-fn">validateUser</span>(<span class="cc-str">'notanemail'</span>, <span class="cc-str">'password123'</span>);
    <span class="cc-fn">expect</span>(<span class="cc-var">res</span>).<span class="cc-fn">toEqual</span>({ ok: <span class="cc-kw">false</span>, error: <span class="cc-str">'Invalid email'</span> });
  });

  <span class="cc-fn">it</span>(<span class="cc-str">'rejects password shorter than 8 chars'</span>, <span class="cc-kw">async</span> () => {
    <span class="cc-kw">const</span> <span class="cc-var">res</span> = <span class="cc-kw">await</span> <span class="cc-fn">validateUser</span>(<span class="cc-str">'a@b.com'</span>, <span class="cc-str">'abc'</span>);
    <span class="cc-fn">expect</span>(<span class="cc-var">res</span>).<span class="cc-fn">toEqual</span>({ ok: <span class="cc-kw">false</span>, error: <span class="cc-str">'Password too short'</span> });
  });

  <span class="cc-fn">it</span>(<span class="cc-str">'returns error when user not found in db'</span>, <span class="cc-kw">async</span> () => {
    <span class="cc-var">db</span>.<span class="cc-var">findByEmail</span>.<span class="cc-fn">mockResolvedValue</span>(<span class="cc-kw">null</span>);
    <span class="cc-kw">const</span> <span class="cc-var">res</span> = <span class="cc-kw">await</span> <span class="cc-fn">validateUser</span>(<span class="cc-str">'a@b.com'</span>, <span class="cc-str">'password123'</span>);
    <span class="cc-fn">expect</span>(<span class="cc-var">res</span>).<span class="cc-fn">toEqual</span>({ ok: <span class="cc-kw">false</span>, error: <span class="cc-str">'User not found'</span> });
  });

  <span class="cc-fn">it</span>(<span class="cc-str">'returns user on correct password'</span>, <span class="cc-kw">async</span> () => {
    <span class="cc-kw">const</span> <span class="cc-var">mockUser</span> = { id: <span class="cc-num">1</span>, email: <span class="cc-str">'a@b.com'</span>, hash: <span class="cc-str">'hash'</span> };
    <span class="cc-var">db</span>.<span class="cc-var">findByEmail</span>.<span class="cc-fn">mockResolvedValue</span>(<span class="cc-var">mockUser</span>);
    <span class="cc-var">bcrypt</span>.<span class="cc-var">compare</span>.<span class="cc-fn">mockResolvedValue</span>(<span class="cc-kw">true</span>);
    <span class="cc-kw">const</span> <span class="cc-var">res</span> = <span class="cc-kw">await</span> <span class="cc-fn">validateUser</span>(<span class="cc-str">'a@b.com'</span>, <span class="cc-str">'password123'</span>);
    <span class="cc-fn">expect</span>(<span class="cc-var">res</span>).<span class="cc-fn">toEqual</span>({ ok: <span class="cc-kw">true</span>, user: <span class="cc-var">mockUser</span> });
  });

  <span class="cc-fn">it</span>(<span class="cc-str">'returns error on wrong password'</span>, <span class="cc-kw">async</span> () => {
    <span class="cc-var">db</span>.<span class="cc-var">findByEmail</span>.<span class="cc-fn">mockResolvedValue</span>({ hash: <span class="cc-str">'hash'</span> });
    <span class="cc-var">bcrypt</span>.<span class="cc-var">compare</span>.<span class="cc-fn">mockResolvedValue</span>(<span class="cc-kw">false</span>);
    <span class="cc-kw">const</span> <span class="cc-var">res</span> = <span class="cc-kw">await</span> <span class="cc-fn">validateUser</span>(<span class="cc-str">'a@b.com'</span>, <span class="cc-str">'wrongpass'</span>);
    <span class="cc-fn">expect</span>(<span class="cc-var">res</span>).<span class="cc-fn">toEqual</span>({ ok: <span class="cc-kw">false</span>, error: <span class="cc-str">'Wrong password'</span> });
  });

});`,
      vitest: `<span class="cc-cm">// Generated by Claude Code — validateUser.test.ts (Vitest)</span>
<span class="cc-kw">import</span> { <span class="cc-var">vi</span>, <span class="cc-var">describe</span>, <span class="cc-var">it</span>, <span class="cc-var">expect</span>, <span class="cc-var">beforeEach</span> } <span class="cc-kw">from</span> <span class="cc-str">'vitest'</span>;
<span class="cc-fn">vi</span>.<span class="cc-fn">mock</span>(<span class="cc-str">'./db'</span>);
<span class="cc-fn">vi</span>.<span class="cc-fn">mock</span>(<span class="cc-str">'bcrypt'</span>);
<span class="cc-cm">// same test structure — replace jest.fn() with vi.fn()</span>`,
      mocha: `<span class="cc-cm">// Generated by Claude Code — validateUser.spec.js (Mocha)</span>
<span class="cc-kw">const</span> <span class="cc-var">sinon</span> = <span class="cc-fn">require</span>(<span class="cc-str">'sinon'</span>);
<span class="cc-kw">const</span> { <span class="cc-var">expect</span> } = <span class="cc-fn">require</span>(<span class="cc-str">'chai'</span>);
<span class="cc-cm">// stub db.findByEmail and bcrypt.compare with sinon</span>`,
    },
    api: {
      tests: 2, cases: 6, cov: 91,
      jest: `<span class="cc-cm">// Generated by Claude Code — fetchProducts.test.js</span>
<span class="cc-kw">import</span> { <span class="cc-var">fetchProducts</span> } <span class="cc-kw">from</span> <span class="cc-str">'./api'</span>;

<span class="cc-fn">global</span>.<span class="cc-var">fetch</span> = <span class="cc-fn">jest</span>.<span class="cc-fn">fn</span>();

<span class="cc-fn">describe</span>(<span class="cc-str">'fetchProducts'</span>, () => {

  <span class="cc-fn">beforeEach</span>(() => <span class="cc-fn">jest</span>.<span class="cc-fn">clearAllMocks</span>());

  <span class="cc-fn">it</span>(<span class="cc-str">'throws if categoryId is missing'</span>, <span class="cc-kw">async</span> () => {
    <span class="cc-kw">await</span> <span class="cc-fn">expect</span>(<span class="cc-fn">fetchProducts</span>())
      .<span class="cc-fn">rejects</span>.<span class="cc-fn">toThrow</span>(<span class="cc-str">'categoryId is required'</span>);
  });

  <span class="cc-fn">it</span>(<span class="cc-str">'calls correct URL with default options'</span>, <span class="cc-kw">async</span> () => {
    <span class="cc-var">fetch</span>.<span class="cc-fn">mockResolvedValue</span>({ ok: <span class="cc-kw">true</span>, <span class="cc-fn">json</span>: () => [] });
    <span class="cc-kw">await</span> <span class="cc-fn">fetchProducts</span>(<span class="cc-str">'electronics'</span>);
    <span class="cc-fn">expect</span>(<span class="cc-var">fetch</span>).<span class="cc-fn">toHaveBeenCalledWith</span>(
      <span class="cc-str">'/api/products?category=electronics&limit=20&page=1&sort=name'</span>
    );
  });

  <span class="cc-fn">it</span>(<span class="cc-str">'respects custom limit, page, sortBy'</span>, <span class="cc-kw">async</span> () => {
    <span class="cc-var">fetch</span>.<span class="cc-fn">mockResolvedValue</span>({ ok: <span class="cc-kw">true</span>, <span class="cc-fn">json</span>: () => [] });
    <span class="cc-kw">await</span> <span class="cc-fn">fetchProducts</span>(<span class="cc-str">'books'</span>, { limit: <span class="cc-num">5</span>, page: <span class="cc-num">2</span>, sortBy: <span class="cc-str">'price'</span> });
    <span class="cc-fn">expect</span>(<span class="cc-var">fetch</span>).<span class="cc-fn">toHaveBeenCalledWith</span>(
      <span class="cc-str">'/api/products?category=books&limit=5&page=2&sort=price'</span>
    );
  });

  <span class="cc-fn">it</span>(<span class="cc-str">'throws on HTTP 500 error'</span>, <span class="cc-kw">async</span> () => {
    <span class="cc-var">fetch</span>.<span class="cc-fn">mockResolvedValue</span>({ ok: <span class="cc-kw">false</span>, status: <span class="cc-num">500</span> });
    <span class="cc-kw">await</span> <span class="cc-fn">expect</span>(<span class="cc-fn">fetchProducts</span>(<span class="cc-str">'books'</span>))
      .<span class="cc-fn">rejects</span>.<span class="cc-fn">toThrow</span>(<span class="cc-str">'HTTP 500'</span>);
  });

});`,
      vitest: `<span class="cc-cm">// Vitest version — use vi.fn() for global fetch mock</span>`,
      mocha: `<span class="cc-cm">// Mocha version — use sinon.stub(global, 'fetch')</span>`,
    },
    cart: {
      tests: 3, cases: 7, cov: 98,
      jest: `<span class="cc-cm">// Generated by Claude Code — addToCart.test.js</span>
<span class="cc-kw">import</span> { <span class="cc-var">addToCart</span> } <span class="cc-kw">from</span> <span class="cc-str">'./cart'</span>;

<span class="cc-fn">describe</span>(<span class="cc-str">'addToCart'</span>, () => {

  <span class="cc-kw">const</span> <span class="cc-var">item</span> = { id: <span class="cc-str">'p1'</span>, name: <span class="cc-str">'Widget'</span>, price: <span class="cc-num">9.99</span> };

  <span class="cc-fn">it</span>(<span class="cc-str">'adds new item to empty cart with qty 1'</span>, () => {
    <span class="cc-kw">const</span> <span class="cc-var">result</span> = <span class="cc-fn">addToCart</span>([], <span class="cc-var">item</span>);
    <span class="cc-fn">expect</span>(<span class="cc-var">result</span>).<span class="cc-fn">toHaveLength</span>(<span class="cc-num">1</span>);
    <span class="cc-fn">expect</span>(<span class="cc-var">result</span>[<span class="cc-num">0</span>]).<span class="cc-fn">toMatchObject</span>({ ...<span class="cc-var">item</span>, qty: <span class="cc-num">1</span> });
  });

  <span class="cc-fn">it</span>(<span class="cc-str">'increments qty for existing item'</span>, () => {
    <span class="cc-kw">const</span> <span class="cc-var">cart</span> = [{ ...<span class="cc-var">item</span>, qty: <span class="cc-num">2</span> }];
    <span class="cc-kw">const</span> <span class="cc-var">result</span> = <span class="cc-fn">addToCart</span>(<span class="cc-var">cart</span>, <span class="cc-var">item</span>);
    <span class="cc-fn">expect</span>(<span class="cc-var">result</span>[<span class="cc-num">0</span>].qty).<span class="cc-fn">toBe</span>(<span class="cc-num">3</span>);
    <span class="cc-fn">expect</span>(<span class="cc-var">result</span>).<span class="cc-fn">toHaveLength</span>(<span class="cc-num">1</span>);
  });

  <span class="cc-fn">it</span>(<span class="cc-str">'does not mutate the original cart array'</span>, () => {
    <span class="cc-kw">const</span> <span class="cc-var">cart</span> = [{ ...<span class="cc-var">item</span>, qty: <span class="cc-num">1</span> }];
    <span class="cc-fn">addToCart</span>(<span class="cc-var">cart</span>, { id: <span class="cc-str">'p2'</span>, price: <span class="cc-num">5</span> });
    <span class="cc-fn">expect</span>(<span class="cc-var">cart</span>).<span class="cc-fn">toHaveLength</span>(<span class="cc-num">1</span>);
  });

  <span class="cc-fn">it</span>(<span class="cc-str">'throws on item without id'</span>, () => {
    <span class="cc-fn">expect</span>(() => <span class="cc-fn">addToCart</span>([], { price: <span class="cc-num">5</span> }))
      .<span class="cc-fn">toThrow</span>(<span class="cc-str">'Invalid item'</span>);
  });

  <span class="cc-fn">it</span>(<span class="cc-str">'throws on zero or negative price'</span>, () => {
    <span class="cc-fn">expect</span>(() => <span class="cc-fn">addToCart</span>([], { id: <span class="cc-str">'x'</span>, price: <span class="cc-num">0</span> }))
      .<span class="cc-fn">toThrow</span>(<span class="cc-str">'Invalid item'</span>);
  });

  <span class="cc-fn">it</span>(<span class="cc-str">'uses custom qty when provided'</span>, () => {
    <span class="cc-kw">const</span> <span class="cc-var">result</span> = <span class="cc-fn">addToCart</span>([], { ...<span class="cc-var">item</span>, qty: <span class="cc-num">3</span> });
    <span class="cc-fn">expect</span>(<span class="cc-var">result</span>[<span class="cc-num">0</span>].qty).<span class="cc-fn">toBe</span>(<span class="cc-num">3</span>);
  });

});`,
      vitest: `<span class="cc-cm">// Vitest version — replace jest imports with vitest</span>`,
      mocha: `<span class="cc-cm">// Mocha version — use chai expect syntax</span>`,
    },
  };

  // ── Modal HTML ─────────────────────────────────
  const MODAL_HTML = `
<div id="cc-overlay">
  <div class="cc-modal">

    <div class="cc-modal-header">
      <div class="cc-dots">
        <span class="d1"></span><span class="d2"></span><span class="d3"></span>
      </div>
      <span class="cc-modal-title">CLAUDE CODE — UNIT TEST GENERATOR</span>
      <span class="cc-version-badge">AI-POWERED</span>
      <button class="cc-close-btn" onclick="CCDemo.close()">✕</button>
    </div>

    <div class="cc-tabs">
      <div class="cc-tab active" onclick="CCDemo.tab('gen')">GENERATOR</div>
      <div class="cc-tab" onclick="CCDemo.tab('explain')">EXPLAIN</div>
    </div>

    <div class="cc-modal-body">

      <!-- GENERATOR TAB -->
      <div id="cc-tab-gen" class="cc-gen-wrap">

        <div>
          <div class="cc-sec-label">QUICK PRESETS</div>
          <div class="cc-presets">
            <span class="cc-preset" onclick="CCDemo.preset('calc',this)">Calculator function</span>
            <span class="cc-preset" onclick="CCDemo.preset('auth',this)">Auth validator</span>
            <span class="cc-preset" onclick="CCDemo.preset('api',this)">API fetch helper</span>
            <span class="cc-preset" onclick="CCDemo.preset('cart',this)">Shopping cart</span>
          </div>
        </div>

        <div>
          <div class="cc-sec-label">PASTE YOUR FUNCTION</div>
          <textarea class="cc-textarea" id="cc-input" placeholder="function yourFunction(params) {\n  // paste your code here...\n}"></textarea>
        </div>

        <div class="cc-controls">
          <select class="cc-fw-select" id="cc-fw">
            <option value="jest">Jest</option>
            <option value="vitest">Vitest</option>
            <option value="mocha">Mocha + Chai</option>
          </select>
          <button class="cc-gen-btn" id="cc-gen-btn" onclick="CCDemo.generate()">⚡ GENERATE TESTS</button>
          <button class="cc-clear-btn" onclick="CCDemo.clear()">✕ CLEAR</button>
        </div>

        <div class="cc-thinking" id="cc-thinking">
          <div class="cc-think-row" id="cc-t1"><div class="cc-think-dot"></div><span>Parsing function signature & parameters...</span></div>
          <div class="cc-think-row" id="cc-t2"><div class="cc-think-dot"></div><span>Identifying happy paths & edge cases...</span></div>
          <div class="cc-think-row" id="cc-t3"><div class="cc-think-dot"></div><span>Generating mock strategies for dependencies...</span></div>
          <div class="cc-think-row" id="cc-t4"><div class="cc-think-dot"></div><span>Writing test cases with assertions...</span></div>
        </div>

        <div class="cc-result" id="cc-result">
          <div class="cc-result-header">
            <div class="cc-result-stats">
              <span class="cc-stat tests" id="cc-stat-tests">—</span>
              <span class="cc-stat cases" id="cc-stat-cases">—</span>
              <span class="cc-stat coverage" id="cc-stat-cov">—</span>
            </div>
            <button class="cc-copy-result-btn" id="cc-copy-result-btn" onclick="CCDemo.copy()">⎘ COPY</button>
          </div>
          <div class="cc-code-output" id="cc-output"></div>
        </div>

      </div>

      <!-- EXPLAIN TAB -->
      <div id="cc-tab-explain" class="cc-explain-wrap" style="display:none">
        <div class="cc-explain-card">
          <h4>CLAUDE CODE LÀM GÌ Ở ĐÂY?</h4>
          <p>Claude Code đọc toàn bộ function, phân tích signature, logic, dependencies — rồi sinh test cases đầy đủ bao gồm happy paths, edge cases, error scenarios và mock strategies.</p>
        </div>
        <div class="cc-explain-card">
          <h4>HAPPY PATHS vs EDGE CASES</h4>
          <p><code>Happy paths</code> — input hợp lệ, function hoạt động đúng. <code>Edge cases</code> — input rỗng, null, undefined, số âm, string thay vì number. Claude Code tự detect từ code thực tế.</p>
        </div>
        <div class="cc-explain-card">
          <h4>MOCK STRATEGY</h4>
          <p>Khi function gọi external dependencies (<code>db</code>, <code>fetch</code>, <code>bcrypt</code>...), Claude Code tự sinh mock/stub phù hợp với framework — <code>jest.mock()</code>, <code>vi.mock()</code>, hay <code>sinon.stub()</code>.</p>
        </div>
        <div class="cc-explain-card">
          <h4>TẠI SAO VIẾT TEST SONG SONG VỚI CODE?</h4>
          <p>Test viết sau khi xong feature thường thiếu edge cases vì dev đã "quen" với logic. Viết test song song (hoặc trước — TDD) giúp phát hiện bug sớm và coverage cao hơn.</p>
        </div>
        <div class="cc-explain-card">
          <h4>LỆNH THỰC TẾ DÙNG VỚI CLAUDE CODE</h4>
          <p><code>claude "Generate Jest unit tests for auth.js with >90% coverage"</code> — Claude Code đọc file, sinh test, tự chạy và fix nếu fail.</p>
        </div>
      </div>

    </div>
  </div>
</div>
`;

  let _activePreset = null;
  let _running = false;

  // ── Public API ─────────────────────────────────
  window.CCDemo = {

    open() {
      document.getElementById('cc-overlay').classList.add('open');
      document.body.style.overflow = 'hidden';
    },

    close() {
      document.getElementById('cc-overlay').classList.remove('open');
      document.body.style.overflow = '';
    },

    tab(name) {
      ['gen', 'explain'].forEach(t => {
        document.getElementById('cc-tab-' + t).style.display = t === name ? '' : 'none';
      });
      document.querySelectorAll('.cc-tab').forEach((el, i) => {
        el.classList.toggle('active', ['gen', 'explain'][i] === name);
      });
    },

    preset(key, el) {
      _activePreset = key;
      document.getElementById('cc-input').value = PRESETS[key] || '';
      document.querySelectorAll('.cc-preset').forEach(p => p.classList.remove('active'));
      el.classList.add('active');
    },

    clear() {
      _activePreset = null;
      document.getElementById('cc-input').value = '';
      document.getElementById('cc-result').classList.remove('show');
      document.getElementById('cc-thinking').classList.remove('show');
      document.querySelectorAll('.cc-preset').forEach(p => p.classList.remove('active'));
      document.querySelectorAll('.cc-think-row').forEach(r => r.classList.remove('show', 'done'));
    },

    async generate() {
      if (_running) return;
      const code = document.getElementById('cc-input').value.trim();
      if (!code) return;

      _running = true;
      document.getElementById('cc-gen-btn').disabled = true;
      document.getElementById('cc-result').classList.remove('show');
      document.getElementById('cc-thinking').classList.add('show');
      document.querySelectorAll('.cc-think-row').forEach(r => r.classList.remove('show', 'done'));

      const rows = ['cc-t1', 'cc-t2', 'cc-t3', 'cc-t4'];
      for (let i = 0; i < rows.length; i++) {
        await new Promise(r => setTimeout(r, 380));
        document.getElementById(rows[i]).classList.add('show');
        if (i > 0) document.getElementById(rows[i - 1]).classList.add('done');
      }
      await new Promise(r => setTimeout(r, 380));
      document.getElementById(rows[rows.length - 1]).classList.add('done');
      await new Promise(r => setTimeout(r, 180));
      document.getElementById('cc-thinking').classList.remove('show');

      const fw   = document.getElementById('cc-fw').value;
      const data = _activePreset ? OUTPUTS[_activePreset] : OUTPUTS.calc;

      document.getElementById('cc-stat-tests').textContent   = data.tests + ' describe blocks';
      document.getElementById('cc-stat-cases').textContent   = data.cases + ' test cases';
      document.getElementById('cc-stat-cov').textContent     = '~' + data.cov + '% coverage';
      document.getElementById('cc-output').innerHTML         = data[fw] || data.jest;
      document.getElementById('cc-result').classList.add('show');

      _running = false;
      document.getElementById('cc-gen-btn').disabled = false;
    },

    copy() {
      const text = document.getElementById('cc-output').innerText;
      navigator.clipboard.writeText(text).catch(() => {});
      const btn = document.getElementById('cc-copy-result-btn');
      btn.textContent = '✓ COPIED';
      btn.classList.add('copied');
      setTimeout(() => { btn.textContent = '⎘ COPY'; btn.classList.remove('copied'); }, 2000);
    },
  };

  // ── Init ───────────────────────────────────────
  function init() {
    document.body.insertAdjacentHTML('beforeend', MODAL_HTML);

    document.getElementById('cc-overlay').addEventListener('click', function (e) {
      if (e.target === this) CCDemo.close();
    });

    document.addEventListener('keydown', e => {
      if (e.key === 'Escape') CCDemo.close();
    });
  }

  if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', init);
  } else {
    init();
  }

})();
